### ISSUE TITLE
Filepath is not valid or allowed

### ISSUE THREAD

**Issue by Nicxe** [robmarkcole/HASS-filesize-sensor#3]
Filepath is no longer allowed

`Filepath /home/homeassistant/.homeassistant/home-assistant_v2.db is not valid or allowed`

It was working fine before, have not changed a thing.

Hassbian
Hass .63.1

**Comment by robmarkcole** [comment]
Please add the path to whitelist_external_dirs
Cheers

**Comment by Nicxe** [comment]
/home/homeassistant/.homeassistant/custom_components/sensor

**Comment by robmarkcole** [comment]
No, should be:
```yaml
homeassistant:
  whitelist_external_dirs:
    - /home/homeassistant/.homeassistant/
```
